FROM adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine@sha256:b6ab039066382d39cfc843914ef1fc624aa60e2a16ede433509ccadd6d995b1f
ADD /target/Auth-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 80
ARG RDS_USER
ENV RDS_USER ${RDS_USER}
ARG RDS_PASS
ENV RDS_PASS ${RDS_PASS}
ARG RDS_URL
ENV RDS_URL ${RDS_URL}
CMD [ "java", "-jar", "app.jar" ]
